apiVersion: apps/v1
kind: Deployment
metadata:
  name: zubayda-and-andrew
  labels:
    app: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes-container
        image: paulbouwer/hello-kubernetes:1.10.1
        ports:
        - containerPort: 8080